spring:
  application:
    name: ms-estudiantes
    description: Gestiona el CRUD de los alumnos, sus perfiles, alergias y matrícula
  
  config:
    import: "optional:classpath:common-properties.yaml"

# Configuración de OpenAPI / Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs/swagger

# Configuración de Scalar UI
scalar:
  enabled: true
  path: /docs/scalar          # Ruta donde se cargará Scalar (ej: http://localhost:8081/docs/scalar)
  url: /v3/api-docs           # Especificación JSON a consumir
  theme: purple               # Temas opcionales: default, moon, purple, solarized, etc.
  darkMode: true