server:
  port: 8086

spring:
  application:
    name: ms-asignaturas
    description: Microservicio para la gestión de asignaturas
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/siga_asignaturas_db
    username: ${DB_USER:root}
    password: ${DB_PASS:dev_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  config:
    import: "optional:classpath:common-properities.yml"

# Circuit Breaker y Feign hacia ms-docentes
feign:
  circuitbreaker:
    enabled: true

services:
  ms-docentes:
    url: ${MS_DOCENTES_URL:http://localhost:8083}

# Configuración de OpenAPI / Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs/swagger

# Configuración de Scalar UI
scalar:
  enabled: true
  path: /docs/scalar          # Ruta donde se cargará Scalar (ej: http://localhost:8081/docs/scalar)
  url: /v3/api-docs           # Especificación JSON a consumir
  theme: purple               # Temas opcionales: default, moon, purple, solarized, etc.
  darkMode: true