server:
  port: 8086

spring:
  application:
    name: ms-asignaturas
    description: Microservicio para la gestiÃ³n de asignaturas
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/siga_asignaturas_db
    username: ${DB_USER:root}
    password: ${DB_PASS:dev_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  config:
    import: "optional:classpath:common-properties.yaml"

# ConfiguraciÃ³n de OpenAPI / Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
# ConfiguraciÃ³n de Scalar UI
scalar:
  enabled: true
  path: /docs/scalar          # Ruta donde se cargarÃ¡ Scalar (ej: http://localhost:8081/docs/scalar)
  url: /v3/api-docs           # EspecificaciÃ³n JSON a consumir
  theme: purple               # Temas opcionales: default, moon, purple, solarized, etc.
  darkMode: true