spring:
  application:
    name: bff-web
  threads:
    virtual:
      enabled: true # Concurrencia masiva eficiente con Java 21
  config:
    import: "optional:classpath:common-properties.yaml"

# URLs de los Microservicios de Dominio
services:
  ms-estudiantes: ${MS_ESTUDIANTES_URL:http://localhost:8082}
  ms-notas: ${MS_NOTAS_URL:http://localhost:8087}

# ConfiguraciÃ³n de OpenAPI / Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs/swagger
# ConfiguraciÃ³n de Scalar UI
scalar:
  enabled: true
  path: /docs/scalar          # Ruta donde se cargarÃ¡ Scalar (ej: http://localhost:8081/docs/scalar)
  url: /v3/api-docs           # EspecificaciÃ³n JSON a consumir
  theme: purple               # Temas opcionales: default, moon, purple, solarized, etc.
  darkMode: true