name: CI Pipeline SIGA

on:
  push:
    branches: [ dev, feature/nxForCD ]

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant execute permission for mvnw
        run: |
          chmod +x apps/backend/*/mvnw || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Monorepo
        run: npx nx run-many -t build --parallel=2